blank_issues_enabled: false
contact_links:
  - name: ✋ I have a question or need support
    url: https://github.com/lowkeyy420/demo/discussions
    about: Get help with using this project or ask general questions about this project
