name: Multi-environment Release

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Release environment"
        required: true
        default: "development"
        type: choice
        options:
          - development
          - production

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Create Release Branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b release-${GITHUB_RUN_ID}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: npx semantic-release
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(release): ${GITHUB_RUN_ID} [skip ci]"
          title: "Release ${GITHUB_RUN_ID}"
          body: "Automated release by semantic-release"
          branch: release-${GITHUB_RUN_ID}
          base: main
